### ISSUE TITLE
Suggestion: Add a commented rule for links with a “rooted” URLs.

### ISSUE THREAD

**Issue by 7studio** [vladocar/Hartija---CSS-Print-Framework#1]
Hi Vladimir,
it could be interesting to add a commented rule for noticing that it is also possible to print the links which have this kind of URL: `/issues/1`.
Here is an exemple:

``` css
/*
a:link[href^="/"]:after, a[href^="/"]:visited:after { 
  content: " (http://www.vcarrer.com" attr(href) ") ";
  font-size: 90%;
}
*/
```

Sorry for the bad manipulation during the opening of the issue.

**Comment by vladocar** [comment]
Excellent suggestion! This will work great for internal links, example "wikipedia.org" internal linking system.

Maybe it will be also interesting to add rules for all the internal links  with .html and .htm at the end. Example "somepage.html"

**Comment by 7studio** [comment]
IMHO, it could be dangerous and difficult to do the same thing with this kind of case.
You took `somepage.html` for example but we can have `./somepage.html`, `../../somepage.html`, `?page=somepage.html` or maybe `file://somepage.html`. It can quickly become complicated to make a CSS selector which will be right in all cases and understandable.

Otherwise, my first proposition is not completely true (sorry) because of the selectors which match absolute URLs without scheme (e.g.: [//www.paulirish.com/2010/the-protocol-relative-url/](http://www.paulirish.com/2010/the-protocol-relative-url/)).
This one seems OK:

``` css
a:link[href^="/"]:not([href^="//"])::after,
a[href^="/"]:not([href^="//"]):visited::after {
  content: " (http://www.vcarrer.com" attr(href) ") ";
  font-size: 90%;
}
```
